### PR TITLE
Run example/test on PR

### PR DESCRIPTION
**Pull request by imcvampire**
Close https://github.com/Kamatera/packer-plugin-kamatera/issues/16

### CODE REVIEW

**Review by OriHoch — CHANGES_REQUESTED** [review]
thanks, looks good

regarding triggering it on pull requests - this could be a security risk, because the kamatera secrets will be available, so someone could open a pull request "steals" those secrets or uses them maliciously, so I think it's better not to allow that or maybe if possible limit it in some way, I'm not too familiar with how it works

**Comment by imcvampire** [comment]
> thanks, looks good
> 
> regarding triggering it on pull requests - this could be a security risk, because the kamatera secrets will be available, so someone could open a pull request "steals" those secrets or uses them maliciously, so I think it's better not to allow that or maybe if possible limit it in some way, I'm not too familiar with how it works

I think the only way is running on the master branch. What do you think?

**Comment by OriHoch** [comment]
yes, running only on pushes to main branch is safe

**Comment by imcvampire** [comment]
@OriHoch Please review again!

**Review by OriHoch — APPROVED** [review]

**Pull request merged**
